# Generated by Django 3.0.4 on 2020-03-11 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='employee',
        ),
    ]
